export const playlistTypes = {
    ADD_PLAYLIST_CATEGORY: 'ADD_PLAYLIST_CATEGORY',
    ADD_SELECTED_SONG: 'ADD_SELECTED_SONG',
    REMOVE_PLAYLIST_CATEGORY: 'REMOVE_PLAYLIST_CATEGORY',
    SET_CATEGORIES: 'SET_CATEGORIES'
}