export const playlistTypes = {
    ADD_PLAYLIST_CATEGORY: 'ADD_PLAYLIST_CATEGORY',
    ADD_SELECTED_SONG: 'ADD_SELECTED_SONG',
    ADD_SONG_TO_NEW_PLAYLIST: 'ADD_SONG_TO_NEW_PLAYLIST',
    CLEAR_UNSPLASH_IMAGE_URL: 'CLEAR_UNSPLASH_IMAGE_URL',
    CLEAR_UPLOADED_IMAGE: 'CLEAR_UPLOADED_IMAGE',
    DISCARD_NEW_PLAYLIST: 'DISCARD_NEW_PLAYLIST',
    GET_SIMILAR_SONGS: 'GET_SIMILAR_SONGS',
    GET_SPOTIFY_RECOMMENDATIONS: 'GET_SPOTIFY_RECOMMENDATIONS',
    REMOVE_PLAYLIST_CATEGORY: 'REMOVE_PLAYLIST_CATEGORY',
    REMOVE_SONG_FROM_NEW_PLAYLIST: 'REMOVE_SONG_FROM_NEW_PLAYLIST',
    REMOVE_SONG_FROM_SUGGESTED_SONGS: 'REMOVE_SONG_FROM_SUGGESTED_SONGS',
    SAVE_PLAYLIST: 'SAVE_PLAYLIST',
    SET_CATEGORIES: 'SET_CATEGORIES',
    SET_MOST_RECENTLY_ADDED_SONG: 'SET_MOST_RECENTLY_ADDED_SONG',
    SET_UNSPLASH_IMAGE_URL: 'SET_UNSPLASH_IMAGE_URL',
    SET_UPLOADED_IMAGE: 'SET_UPLOADED_IMAGE'
}