export const userTypes = {
    ADD_USER_PLAYLIST: 'ADD_USER_PLAYLIST',
    SET_LOGGED_IN_USER: 'SET_LOGGED_IN_USER',
    SET_LOGGING_IN_TO_SAVE: 'SET_LOGGING_IN_TO_SAVE',
    SET_PASSWORD: 'SET_PASSWORD',
    SET_REGISTRATION_PASSWORD: 'SET_REGISRATION_PASSWORD',
    SET_REGISTRATION_USERNAME: 'SET_REGISTRATION_USERNAME',
    SET_USERNAME: 'SET_USERNAME'
}